
import Header from "@/components/Header";
import "./globals.css";
import Footer from "@/components/Footer";
import { Arya } from 'next/font/google'

export const metadata = {
  title: "Next Tutorial",
  description: "Generated by create next app",
};

const arya = Arya({
  weight: ['400', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={arya.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}

